name: 'Run Benchmarks'

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  benchmarks:
    runs-on: gha-mm-scale-set-ubuntu-22.04-amd64-med
    container:
      image: cimg/node:20.18-browsers
    steps:
      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@caching
        with:
          should-cache-restore: false

      - name: Download artifact prep-build-test-webpack
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          pattern: prep-build-test-webpack
          merge-multiple: true

      - name: Configure Xvfb
        run: Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Run the benchmark
        run: ${{ inputs.command }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: pageload
          path: test-artifacts/chrome/benchmark/pageload.json
          retention-days: 5
