on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      command:
        required: true
        type: string

# It's not easy to pass this in from main.yml, so define it again
# This should become a GitHub ENV variable
env:
  USE_CACHING: 'true'

jobs:
  benchmarks:
    name: ${{ inputs.name }}
    runs-on: gha-mm-scale-set-ubuntu-22.04-amd64-med
    container:
      image: cimg/node:22.13-browsers
    steps:
      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@caching
        with:
          should-cache-restore: ${{ env.USE_CACHING }}

      - name: Download artifact prep-build-test-webpack
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          pattern: prep-build-test-webpack
          merge-multiple: true

      - name: Configure Xvfb
        run: Xvfb -ac :99 -screen 0 1280x1024x16 &

      - name: Run the benchmark
        run: ${{ inputs.command }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: test-artifacts/chrome/benchmark/
          retention-days: 5
