name: Check PR has required labels
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  check-pr-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@caching

      - name: Check PR has required labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run check-pr-has-required-labels
