name: Check Attributions

on:
  push:
    branches: Version-v*

jobs:
  check-attributions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@caching

      - name: Check attributions changes
        run: yarn attributions:check
